### ISSUE TITLE
ofxSuperCollider with oF0.9

### ISSUE THREAD

**Issue by chankalun** [genekogan/ofxSuperCollider#1]
Hello I am trying to use ofxSuperCollider with oF0.9 and the following error has appeared:

'tr1/unordered_map' file not found

I have tried this but with no luck:
//typedef std::tr1::unordered_map<string, float> dictionary;
using tr1;

May I ask how could I resolve this please? 

Cheers,
Karen

**Comment by genekogan** [comment]
this has been fixed. it should work for 0.9 now.

**Comment by chankalun** [comment]
Thanks :))) x
